config/routes.rb
DemoApp::Application.routes.draw do
  resources :go_slim_sequences

  resources :go_slims

  resources :auto24h_r2_fold_changes

  resources :hetero24h_r2_fold_changes

  resources :hetero1h_r2_fold_changes

  resources :auto1h_r2_fold_changes

  resources :leaders

  resources :auto24h_fold_changes

  resources :auto1h_fold_changes

  resources :hetero24h_fold_changes

  resources :hetero1h_fold_changes

  resources :treatments

  resources :fold_changes

  resources :de_analyses

  resources :experiments

  resources :gene_ontologies

  resources :interpros

  resources :annotation_sources

  resources :annotations

  resources :features

  resources :sequences

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/password', :to => 'users#password'
  match '/submit', :to => 'blast#submit'
  match '/about', :to => 'pages#about'
  match '/data', :to => 'pages#data'
  match '/photo', :to => 'pages#photo'
  match '/wait', :to => 'blast#wait'

  match '/result', :to => 'blast#result'

  get "pages/blast"

  get "pages/about"

  get "pages/photo"

  get "pages/data"

  get "blast_dbs/fastasearch"  
  match '/fastasearch', :to => 'blast_dbs#fastasearch'

  get "blast_dbs/sequence_map"
  match '/sequence_map', :to => 'blast_dbs#sequence_map'

  get "blast_dbs/aa_sequence_map"
  match '/aa_sequence_map', :to => 'blast_dbs#aa_sequence_map'

  get "de_data/heatmap"
  match '/heatmap', :to => 'de_data#heatmap'

  get "de_data/go_summary"
  match '/go_summary', :to => 'de_data#go_summary'

  get "de_data/go_json"
  match '/go_json', :to => 'de_data#go_json'

  get "de_data/cluster_annot"
  match '/cluster_annot', :to => 'de_data#cluster_annot'

  get "leaders/detail"
  match '/leader_detail', :to => 'leaders#detail'

  get "users/password"
  get "users/new"
  resources :microposts

  resources :de_data
  resources :blast_dbs

  root :to => 'pages#blast'

end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  has_many :de_data
  has_many :leaders
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  # GET /treatments
  # GET /treatments.xml
  def index
    @treatments = Treatment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @treatments }
    end
  end

  # GET /treatments/1
  # GET /treatments/1.xml
  def show
    @treatment = Treatment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @treatment }
    end
  end

  # GET /treatments/new
  # GET /treatments/new.xml
  def new
    @treatment = Treatment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @treatment }
    end
  end

  # GET /treatments/1/edit
  def edit
    @treatment = Treatment.find(params[:id])
  end

  # POST /treatments
  # POST /treatments.xml
  def create
    @treatment = Treatment.new(params[:treatment])

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to(@treatment, :notice => 'Treatment was successfully created.') }
        format.xml  { render :xml => @treatment, :status => :created, :location => @treatment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @treatment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /treatments/1
  # PUT /treatments/1.xml
  def update
    @treatment = Treatment.find(params[:id])

    respond_to do |format|
      if @treatment.update_attributes(params[:treatment])
        format.html { redirect_to(@treatment, :notice => 'Treatment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @treatment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.xml
  def destroy
    @treatment = Treatment.find(params[:id])
    @treatment.destroy

    respond_to do |format|
      format.html { redirect_to(treatments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= form_for(@treatment) do |f| %>
  <% if @treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% @treatment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :ordering %><br />
    <%= f.text_field :ordering %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing treatment</h1>

<%= render 'form' %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<h1>Listing treatments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Ordering</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @treatments.each do |treatment| %>
  <tr>
    <td><%= treatment.name %></td>
    <td><%= treatment.description %></td>
    <td><%= treatment.ordering %></td>
    <td><%= link_to 'Show', treatment %></td>
    <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
    <td><%= link_to 'Destroy', treatment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Treatment', new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New treatment</h1>

<%= render 'form' %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @treatment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @treatment.description %>
</p>

<p>
  <b>Ordering:</b>
  <%= @treatment.ordering %>
</p>


<%= link_to 'Edit', edit_treatment_path(@treatment) %> |
<%= link_to 'Back', treatments_path %>