config/routes.rb
DemoApp::Application.routes.draw do
  resources :go_slim_sequences

  resources :go_slims

  resources :auto24h_r2_fold_changes

  resources :hetero24h_r2_fold_changes

  resources :hetero1h_r2_fold_changes

  resources :auto1h_r2_fold_changes

  resources :leaders

  resources :auto24h_fold_changes

  resources :auto1h_fold_changes

  resources :hetero24h_fold_changes

  resources :hetero1h_fold_changes

  resources :treatments

  resources :fold_changes

  resources :de_analyses

  resources :experiments

  resources :gene_ontologies

  resources :interpros

  resources :annotation_sources

  resources :annotations

  resources :features

  resources :sequences

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/password', :to => 'users#password'
  match '/submit', :to => 'blast#submit'
  match '/about', :to => 'pages#about'
  match '/data', :to => 'pages#data'
  match '/photo', :to => 'pages#photo'
  match '/wait', :to => 'blast#wait'

  match '/result', :to => 'blast#result'

  get "pages/blast"

  get "pages/about"

  get "pages/photo"

  get "pages/data"

  get "blast_dbs/fastasearch"  
  match '/fastasearch', :to => 'blast_dbs#fastasearch'

  get "blast_dbs/sequence_map"
  match '/sequence_map', :to => 'blast_dbs#sequence_map'

  get "blast_dbs/aa_sequence_map"
  match '/aa_sequence_map', :to => 'blast_dbs#aa_sequence_map'

  get "de_data/heatmap"
  match '/heatmap', :to => 'de_data#heatmap'

  get "de_data/go_summary"
  match '/go_summary', :to => 'de_data#go_summary'

  get "de_data/go_json"
  match '/go_json', :to => 'de_data#go_json'

  get "de_data/cluster_annot"
  match '/cluster_annot', :to => 'de_data#cluster_annot'

  get "leaders/detail"
  match '/leader_detail', :to => 'leaders#detail'

  get "users/password"
  get "users/new"
  resources :microposts

  resources :de_data
  resources :blast_dbs

  root :to => 'pages#blast'

end

app/models/fold_change.rb
class FoldChange < ActiveRecord::Base
  belongs_to :de_analysis
  belongs_to :sequence
  belongs_to :treatment
  belongs_to :base_treatment, :class_name => "Treatment", :foreign_key => "base_treatment_id"

def self.load filename, de_analysis_id, treatment_id, base_treatment_id
#1 - symbol
#5 - fold change
#6 - log2 fold change
#7 - pval
#8 - fdr

  file = File.open("#{Rails.root}/#{filename}", 'rb')
  while(line = file.gets)
    parts = line.split
    next if parts[0] == "\"id\""
    seq_name = parts[1][1..(parts[1].size - 2)] 
    seq = Sequence.where(:accession => seq_name ).first
    FoldChange.create(:log2fc => parts[6], :fdr => parts[8], :pval => parts[7], :de_analysis_id => de_analysis_id, :treatment_id => treatment_id, :base_treatment_id => base_treatment_id, :sequence_id => seq.id) 
  end
end
end

app/controllers/fold_changes_controller.rb
class FoldChangesController < ApplicationController
  # GET /fold_changes
  # GET /fold_changes.xml
  def index
    @fold_changes = FoldChange.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fold_changes }
    end
  end

  # GET /fold_changes/1
  # GET /fold_changes/1.xml
  def show
    @fold_change = FoldChange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fold_change }
    end
  end

  # GET /fold_changes/new
  # GET /fold_changes/new.xml
  def new
    @fold_change = FoldChange.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fold_change }
    end
  end

  # GET /fold_changes/1/edit
  def edit
    @fold_change = FoldChange.find(params[:id])
  end

  # POST /fold_changes
  # POST /fold_changes.xml
  def create
    @fold_change = FoldChange.new(params[:fold_change])

    respond_to do |format|
      if @fold_change.save
        format.html { redirect_to(@fold_change, :notice => 'Fold change was successfully created.') }
        format.xml  { render :xml => @fold_change, :status => :created, :location => @fold_change }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fold_change.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fold_changes/1
  # PUT /fold_changes/1.xml
  def update
    @fold_change = FoldChange.find(params[:id])

    respond_to do |format|
      if @fold_change.update_attributes(params[:fold_change])
        format.html { redirect_to(@fold_change, :notice => 'Fold change was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fold_change.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fold_changes/1
  # DELETE /fold_changes/1.xml
  def destroy
    @fold_change = FoldChange.find(params[:id])
    @fold_change.destroy

    respond_to do |format|
      format.html { redirect_to(fold_changes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/fold_changes_helper.rb
module FoldChangesHelper
end

app/views/fold_changes/_form.html.erb
<%= form_for(@fold_change) do |f| %>
  <% if @fold_change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fold_change.errors.count, "error") %> prohibited this fold_change from being saved:</h2>

      <ul>
      <% @fold_change.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :log2fc %><br />
    <%= f.text_field :log2fc %>
  </div>
  <div class="field">
    <%= f.label :fdr %><br />
    <%= f.text_field :fdr %>
  </div>
  <div class="field">
    <%= f.label :pval %><br />
    <%= f.text_field :pval %>
  </div>
  <div class="field">
    <%= f.label :de_analysis_id %><br />
    <%= f.text_field :de_analysis_id %>
  </div>
  <div class="field">
    <%= f.label :treatment_id %><br />
    <%= f.text_field :treatment_id %>
  </div>
  <div class="field">
    <%= f.label :base_treatment_id %><br />
    <%= f.text_field :base_treatment_id %>
  </div>
  <div class="field">
    <%= f.label :sequence_id %><br />
    <%= f.text_field :sequence_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fold_changes/edit.html.erb
<h1>Editing fold_change</h1>

<%= render 'form' %>

<%= link_to 'Show', @fold_change %> |
<%= link_to 'Back', fold_changes_path %>

app/views/fold_changes/index.html.erb
<h1>Listing fold_changes</h1>

<table>
  <tr>
    <th>Log2fc</th>
    <th>Fdr</th>
    <th>Pval</th>
    <th>De analysis</th>
    <th>Treatment</th>
    <th>Base treatment</th>
    <th>Sequence</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fold_changes.each do |fold_change| %>
  <tr>
    <td><%= fold_change.log2fc %></td>
    <td><%= fold_change.fdr %></td>
    <td><%= fold_change.pval %></td>
    <td><%= fold_change.de_analysis_id %></td>
    <td><%= fold_change.treatment_id %></td>
    <td><%= fold_change.base_treatment_id %></td>
    <td><%= fold_change.sequence_id %></td>
    <td><%= link_to 'Show', fold_change %></td>
    <td><%= link_to 'Edit', edit_fold_change_path(fold_change) %></td>
    <td><%= link_to 'Destroy', fold_change, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fold change', new_fold_change_path %>

app/views/fold_changes/new.html.erb
<h1>New fold_change</h1>

<%= render 'form' %>

<%= link_to 'Back', fold_changes_path %>

app/views/fold_changes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Log2fc:</b>
  <%= @fold_change.log2fc %>
</p>

<p>
  <b>Fdr:</b>
  <%= @fold_change.fdr %>
</p>

<p>
  <b>Pval:</b>
  <%= @fold_change.pval %>
</p>

<p>
  <b>De analysis:</b>
  <%= @fold_change.de_analysis_id %>
</p>

<p>
  <b>Treatment:</b>
  <%= @fold_change.treatment_id %>
</p>

<p>
  <b>Base treatment:</b>
  <%= @fold_change.base_treatment_id %>
</p>

<p>
  <b>Sequence:</b>
  <%= @fold_change.sequence_id %>
</p>


<%= link_to 'Edit', edit_fold_change_path(@fold_change) %> |
<%= link_to 'Back', fold_changes_path %>