config/routes.rb
DemoApp::Application.routes.draw do
  resources :go_slim_sequences

  resources :go_slims

  resources :auto24h_r2_fold_changes

  resources :hetero24h_r2_fold_changes

  resources :hetero1h_r2_fold_changes

  resources :auto1h_r2_fold_changes

  resources :leaders

  resources :auto24h_fold_changes

  resources :auto1h_fold_changes

  resources :hetero24h_fold_changes

  resources :hetero1h_fold_changes

  resources :treatments

  resources :fold_changes

  resources :de_analyses

  resources :experiments

  resources :gene_ontologies

  resources :interpros

  resources :annotation_sources

  resources :annotations

  resources :features

  resources :sequences

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/password', :to => 'users#password'
  match '/submit', :to => 'blast#submit'
  match '/about', :to => 'pages#about'
  match '/data', :to => 'pages#data'
  match '/photo', :to => 'pages#photo'
  match '/wait', :to => 'blast#wait'

  match '/result', :to => 'blast#result'

  get "pages/blast"

  get "pages/about"

  get "pages/photo"

  get "pages/data"

  get "blast_dbs/fastasearch"  
  match '/fastasearch', :to => 'blast_dbs#fastasearch'

  get "blast_dbs/sequence_map"
  match '/sequence_map', :to => 'blast_dbs#sequence_map'

  get "blast_dbs/aa_sequence_map"
  match '/aa_sequence_map', :to => 'blast_dbs#aa_sequence_map'

  get "de_data/heatmap"
  match '/heatmap', :to => 'de_data#heatmap'

  get "de_data/go_summary"
  match '/go_summary', :to => 'de_data#go_summary'

  get "de_data/go_json"
  match '/go_json', :to => 'de_data#go_json'

  get "de_data/cluster_annot"
  match '/cluster_annot', :to => 'de_data#cluster_annot'

  get "leaders/detail"
  match '/leader_detail', :to => 'leaders#detail'

  get "users/password"
  get "users/new"
  resources :microposts

  resources :de_data
  resources :blast_dbs

  root :to => 'pages#blast'

end

app/models/go_slim_sequence.rb
class GoSlimSequence < ActiveRecord::Base
  attr_accessible :evidence_code, :gene_ontology_id, :gene_symbol, :go_seq_description, :go_slim_id, :sequence_id, :taxon

  belongs_to :go_slim
  belongs_to :sequence
  belongs_to :gene_ontology

  def GoSlimSequence.load file_name
    file = File.open("#{Rails.root}/#{file_name}", 'rb')

    while(line = file.gets)
      parts = line.split("\t")
      if(parts[0] =~ /^s\d_\d+$/)
        next
      end
      go_accession  = parts[4]
      go = GeneOntology.find_by_accession go_accession
      seq_accession =  parts[16].chomp
      seq = Sequence.where( :accession => seq_accession ).first
      taxon = parts[12].split(?:)[1]
      begin
        GoSlimSequence.create(:sequence_id => seq.id, :gene_ontology_id => go.id, :go_slim_id => 1,
                              :evidence_code => parts[6], :gene_symbol => parts[2], :go_seq_description => parts[9], :taxon => taxon)
      rescue ActiveRecord::RecordNotUnique
        #do nil
      end
    end
  end
end

app/controllers/go_slim_sequences_controller.rb
class GoSlimSequencesController < ApplicationController
  # GET /go_slim_sequences
  # GET /go_slim_sequences.json
  def index
    @go_slim_sequences = GoSlimSequence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @go_slim_sequences }
    end
  end

  # GET /go_slim_sequences/1
  # GET /go_slim_sequences/1.json
  def show
    @go_slim_sequence = GoSlimSequence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @go_slim_sequence }
    end
  end

  # GET /go_slim_sequences/new
  # GET /go_slim_sequences/new.json
  def new
    @go_slim_sequence = GoSlimSequence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @go_slim_sequence }
    end
  end

  # GET /go_slim_sequences/1/edit
  def edit
    @go_slim_sequence = GoSlimSequence.find(params[:id])
  end

  # POST /go_slim_sequences
  # POST /go_slim_sequences.json
  def create
    @go_slim_sequence = GoSlimSequence.new(params[:go_slim_sequence])

    respond_to do |format|
      if @go_slim_sequence.save
        format.html { redirect_to @go_slim_sequence, notice: 'Go slim sequence was successfully created.' }
        format.json { render json: @go_slim_sequence, status: :created, location: @go_slim_sequence }
      else
        format.html { render action: "new" }
        format.json { render json: @go_slim_sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /go_slim_sequences/1
  # PUT /go_slim_sequences/1.json
  def update
    @go_slim_sequence = GoSlimSequence.find(params[:id])

    respond_to do |format|
      if @go_slim_sequence.update_attributes(params[:go_slim_sequence])
        format.html { redirect_to @go_slim_sequence, notice: 'Go slim sequence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @go_slim_sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /go_slim_sequences/1
  # DELETE /go_slim_sequences/1.json
  def destroy
    @go_slim_sequence = GoSlimSequence.find(params[:id])
    @go_slim_sequence.destroy

    respond_to do |format|
      format.html { redirect_to go_slim_sequences_url }
      format.json { head :no_content }
    end
  end
end

app/views/go_slim_sequences/_form.html.erb
<%= form_for(@go_slim_sequence) do |f| %>
  <% if @go_slim_sequence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@go_slim_sequence.errors.count, "error") %> prohibited this go_slim_sequence from being saved:</h2>

      <ul>
      <% @go_slim_sequence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sequence_id %><br />
    <%= f.text_field :sequence_id %>
  </div>
  <div class="field">
    <%= f.label :gene_ontology_id %><br />
    <%= f.text_field :gene_ontology_id %>
  </div>
  <div class="field">
    <%= f.label :go_slim_id %><br />
    <%= f.text_field :go_slim_id %>
  </div>
  <div class="field">
    <%= f.label :go_seq_description %><br />
    <%= f.text_field :go_seq_description %>
  </div>
  <div class="field">
    <%= f.label :gene_symbol %><br />
    <%= f.text_field :gene_symbol %>
  </div>
  <div class="field">
    <%= f.label :taxon %><br />
    <%= f.text_field :taxon %>
  </div>
  <div class="field">
    <%= f.label :evidence_code %><br />
    <%= f.text_field :evidence_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/go_slim_sequences/edit.html.erb
<h1>Editing go_slim_sequence</h1>

<%= render 'form' %>

<%= link_to 'Show', @go_slim_sequence %> |
<%= link_to 'Back', go_slim_sequences_path %>

app/views/go_slim_sequences/index.html.erb
<h1>Listing go_slim_sequences</h1>

<table>
  <tr>
    <th>Sequence</th>
    <th>Gene ontology</th>
    <th>Go slim</th>
    <th>Go seq description</th>
    <th>Gene symbol</th>
    <th>Taxon</th>
    <th>Evidence code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @go_slim_sequences.each do |go_slim_sequence| %>
  <tr>
    <td><%= go_slim_sequence.sequence_id %></td>
    <td><%= go_slim_sequence.gene_ontology_id %></td>
    <td><%= go_slim_sequence.go_slim_id %></td>
    <td><%= go_slim_sequence.go_seq_description %></td>
    <td><%= go_slim_sequence.gene_symbol %></td>
    <td><%= go_slim_sequence.taxon %></td>
    <td><%= go_slim_sequence.evidence_code %></td>
    <td><%= link_to 'Show', go_slim_sequence %></td>
    <td><%= link_to 'Edit', edit_go_slim_sequence_path(go_slim_sequence) %></td>
    <td><%= link_to 'Destroy', go_slim_sequence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Go slim sequence', new_go_slim_sequence_path %>

app/views/go_slim_sequences/new.html.erb
<h1>New go_slim_sequence</h1>

<%= render 'form' %>

<%= link_to 'Back', go_slim_sequences_path %>

app/views/go_slim_sequences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sequence:</b>
  <%= @go_slim_sequence.sequence_id %>
</p>

<p>
  <b>Gene ontology:</b>
  <%= @go_slim_sequence.gene_ontology_id %>
</p>

<p>
  <b>Go slim:</b>
  <%= @go_slim_sequence.go_slim_id %>
</p>

<p>
  <b>Go seq description:</b>
  <%= @go_slim_sequence.go_seq_description %>
</p>

<p>
  <b>Gene symbol:</b>
  <%= @go_slim_sequence.gene_symbol %>
</p>

<p>
  <b>Taxon:</b>
  <%= @go_slim_sequence.taxon %>
</p>

<p>
  <b>Evidence code:</b>
  <%= @go_slim_sequence.evidence_code %>
</p>


<%= link_to 'Edit', edit_go_slim_sequence_path(@go_slim_sequence) %> |
<%= link_to 'Back', go_slim_sequences_path %>