config/routes.rb
DemoApp::Application.routes.draw do
  resources :go_slim_sequences

  resources :go_slims

  resources :auto24h_r2_fold_changes

  resources :hetero24h_r2_fold_changes

  resources :hetero1h_r2_fold_changes

  resources :auto1h_r2_fold_changes

  resources :leaders

  resources :auto24h_fold_changes

  resources :auto1h_fold_changes

  resources :hetero24h_fold_changes

  resources :hetero1h_fold_changes

  resources :treatments

  resources :fold_changes

  resources :de_analyses

  resources :experiments

  resources :gene_ontologies

  resources :interpros

  resources :annotation_sources

  resources :annotations

  resources :features

  resources :sequences

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/password', :to => 'users#password'
  match '/submit', :to => 'blast#submit'
  match '/about', :to => 'pages#about'
  match '/data', :to => 'pages#data'
  match '/photo', :to => 'pages#photo'
  match '/wait', :to => 'blast#wait'

  match '/result', :to => 'blast#result'

  get "pages/blast"

  get "pages/about"

  get "pages/photo"

  get "pages/data"

  get "blast_dbs/fastasearch"  
  match '/fastasearch', :to => 'blast_dbs#fastasearch'

  get "blast_dbs/sequence_map"
  match '/sequence_map', :to => 'blast_dbs#sequence_map'

  get "blast_dbs/aa_sequence_map"
  match '/aa_sequence_map', :to => 'blast_dbs#aa_sequence_map'

  get "de_data/heatmap"
  match '/heatmap', :to => 'de_data#heatmap'

  get "de_data/go_summary"
  match '/go_summary', :to => 'de_data#go_summary'

  get "de_data/go_json"
  match '/go_json', :to => 'de_data#go_json'

  get "de_data/cluster_annot"
  match '/cluster_annot', :to => 'de_data#cluster_annot'

  get "leaders/detail"
  match '/leader_detail', :to => 'leaders#detail'

  get "users/password"
  get "users/new"
  resources :microposts

  resources :de_data
  resources :blast_dbs

  root :to => 'pages#blast'

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_many :de_analyses, :dependent => :destroy
  has_many :leaders
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  # GET /experiments
  # GET /experiments.xml
  def index
    @experiments = Experiment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @experiments }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.xml
  def show
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @experiment }
    end
  end

  # GET /experiments/new
  # GET /experiments/new.xml
  def new
    @experiment = Experiment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.xml
  def create
    @experiment = Experiment.new(params[:experiment])

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to(@experiment, :notice => 'Experiment was successfully created.') }
        format.xml  { render :xml => @experiment, :status => :created, :location => @experiment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @experiment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.xml
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to(@experiment, :notice => 'Experiment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @experiment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.xml
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to(experiments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<h1>Listing experiments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @experiments.each do |experiment| %>
  <tr>
    <td><%= experiment.name %></td>
    <td><%= experiment.description %></td>
    <td><%= link_to 'Show', experiment %></td>
    <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
    <td><%= link_to 'Destroy', experiment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Experiment', new_experiment_path %>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @experiment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @experiment.description %>
</p>


<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>